apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sampleapp-dotnet
  namespace: ad54321
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ad54321
  syncPolicy:
    automated: {}
  source:
    repoURL: https://bitbucket.org/mattgmoser/schwab-iac-gke-config.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ad54321