apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-test
  namespace: ad54321
spec:
  project: ad54321
  source:
    chart: dotnet-template
    repoURL: https://lab-registry.wwtlab.net/helm-charts/dotnet-template
    targetRevision: 0.1.0
    helm:
      releaseName: dotnet-template
      parameters:
        - name: virtualService.enabled
          value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ad54321